service:
  type: NodePort
  ports:
    tools:
      nodePort: 30885

otel:
  tracing:
    enabled: true
    exporter:
      otlp:
        endpoint: http://host.docker.internal:4317
        timeout: 15
        insecure: true