binds:
  - port: 30805
    listeners:
      - routes:
          - policies:
              cors:
                allowOrigins:
                  - "*"
                allowHeaders:
                  - mcp-protocol-version
                  - content-type
            backends:
              - mcp:
                  name: default
                  targets:
                    - name: kagent-tools
                      stdio:
                        cmd: kagent-tools
                        args: ["--stdio", "--kubeconfig", "~/.kube/config"]