name: CI Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    env:
      VERSION: v0.0.1-test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/amd64,linux/arm64
          version: v0.23.0
          use: 'true'
      - name: Run make build
        env:
          DOCKER_BUILDKIT: 1
          BUILDX_BUILDER_NAME: kagent-builder-v0.23.0
          DOCKER_BUILD_ARGS: >-
            --cache-from=type=gha
            --cache-to=type=gha,mode=max
            --platform=linux/amd64,linux/arm64
            --output=type=tar,dest=/dev/null
          DOCKER_REPO: "${{ github.repository_owner }}/tools"
          DOCKER_BUILDER: "docker buildx"
        run: make docker-build
        working-directory: ./

  go-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.24"
          cache: true

      - name: Run cmd/main.go tests
        working-directory: .
        run: |
          make test

  go-e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.24"
          cache: true

      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1
        with:
          cluster_name: kagent
          config: scripts/kind/kind-config.yaml

      - name: Run cmd/main.go tests
        working-directory: .
        run: |
          make e2e

  helm-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v4.2.0
        with:
          version: v3.17.0

      - name: Install unittest plugin
        run: |
          helm plugin install https://github.com/helm-unittest/helm-unittest

      - name: Chart init
        run: |
          make helm-version

      - name: Run helm unit tests
        run: |
          make helm-test
